# Generated by Django 4.2.30 on 2026-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_rename_target_id_auditlog_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
