version: '3.8'

services:
  db:
    image: postgres:16
    container_name: private-cloud-db-1
    environment:
      POSTGRES_DB: ${DB_NAME:-cloud_db}
      POSTGRES_USER: ${DB_USER:-cloud_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-@Sukaslamet123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: private-cloud-redis-1
    ports:
      - "6379:6379"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: private-cloud-elasticsearch-1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always

volumes:
  postgres_data:
  es_data:
